global:
    scrape_interval: 15s

scrape_configs:
    - job_name: 'django'
      scrape_interval: 5s
      static_configs:
        - targets: ['backend:8000']

    - job_name: 'node'
      scrape_interval: 5s
      static_configs:
        - targets: ['nodeexporter:9100']

    - job_name: 'cadvisor'
      scrape_interval: 5s
      static_configs:
        - targets: ['cadvisor:8080']